name: SecureQR Backend CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DigitalOcean Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login registry.digitalocean.com -u do --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t registry.digitalocean.com/secureqr-registry/secureqr-backend:latest .

      - name: Push to DigitalOcean Registry
        run: |
          docker push registry.digitalocean.com/secureqr-registry/secureqr-backend:latest
